apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
      - name: game-service
        image: mmroomi/lugx-game-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          value: "lugx_user"
        - name: DB_PASSWORD
          value: "lugx_pass"
        - name: DB_HOST
          value: "host.docker.internal"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "lugx_db"

