# .github/workflows/build-and-push-fastapi.yml
name: Build & Push FastAPI Image

on:
  push:
    branches: [ "main" ]       # build on pushes to main
    tags: [ "v*" ]             # and on version tags like v1.0.0
  workflow_dispatch:           # allow manual runs

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare tags
        id: prep
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/game-service-lugx
          SHA_TAG=${IMAGE}:sha-${GITHUB_SHA::7}
          # Default tags (latest + sha)
          TAGS="${IMAGE}:latest,${SHA_TAG}"
          # If this is a git tag push (e.g., v1.2.3), add it as a tag
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION_TAG=${IMAGE}:${GITHUB_REF_NAME}
            TAGS="${TAGS},${VERSION_TAG}"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
